---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-ingwatcher
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-ingwatcher
rules:
- apiGroups:
    - "extensions"
  resources:
    - ingresses
  verbs: 
    - get
    - list
    - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-ingwatcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-ingwatcher
subjects:
- kind: ServiceAccount
  name: kube-ingwatcher
  namespace: kube-system
